GET http://localhost:3000/posts
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTcxMDg1NTc0NCwiZXhwIjoxNzEwODU1Nzc3fQ.WS9VQf63O7t5mGCbvGUqeayMZ40piy9U1axC8cgXorE

### 
POST http://localhost:4000/token 
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTcxMDg1NzIzMH0.Bt5SMCuxIleiFdlog1TzOWzf9MCoKrz7CVTdOI-yr68" 
}







### 
POST http://localhost:4000/login
Content-Type: application/json

{
    "userName":"Kyle"
}